# -- Job Configuration
username: "johndoe"
queue: "default"
# wallTimeSeconds: 14400  # Optional: e.g., 4 hours = 14400 seconds. Leave empty to disable.
orgPrefix: org.example.com

# -- Compute Requirements
resources:
  cpu: "2"
  memory: "2Gi"
  volcano.sh/vgpu-number: null

# -- Storage Configuration (NFS)
nfs:
  mounts: []
#    - server: "10.0.0.5"
#      path: "/export/users/namdp"
#      mountPath: "/home/jovyan/work"
#      readOnly: false
#    - server: "10.0.0.6"
#      path: "/export/datasets/imagenet"
#      mountPath: "/data/imagenet"
#      readOnly: true

# -- Container Image
image:
  repository: "jupyter/base-notebook"
  tag: "latest"
